version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: duty_schedule_bot_local
    volumes:
      - .:/app
    command: bot
  scheduler:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: duty_schedule_bot_local
    volumes:
      - .:/app
    command: scheduler
  redis:
    image: redis:alpine
